{
    "action": "released",
    "release": {
        "assets": [
            {
                "browser_download_url": "https://github.com/isabelschoeps-thiel/seismic-source/releases/download/seismic_source_08_02_2026/dtd-2014.zip",
                "content_type": "application/zip",
                "created_at": "2026-02-08T00:51:12Z",
                "digest": "sha256:cd002b6ef2c6f3c990d1a31b8b6a5ece786a41269006566c7a8be9ec748ac9a2",
                "download_count": 0,
                "id": 352375145,
                "label": null,
                "name": "dtd-2014.zip",
                "node_id": "RA_kwDOQ6NDkM4VANFp",
                "size": 25334317,
                "state": "uploaded",
                "updated_at": "2026-02-08T00:51:17Z",
                "uploader": {
                    "avatar_url": "https://avatars.githubusercontent.com/u/246072696?v=4",
                    "events_url": "https://api.github.com/users/isabelschoeps-thiel/events{/privacy}",
                    "followers_url": "https://api.github.com/users/isabelschoeps-thiel/followers",
                    "following_url": "https://api.github.com/users/isabelschoeps-thiel/following{/other_user}",
                    "gists_url": "https://api.github.com/users/isabelschoeps-thiel/gists{/gist_id}",
                    "gravatar_id": "",
                    "html_url": "https://github.com/isabelschoeps-thiel",
                    "id": 246072696,
                    "login": "isabelschoeps-thiel",
                    "node_id": "246072696",
                    "organizations_url": "https://api.github.com/users/isabelschoeps-thiel/orgs",
                    "received_events_url": "https://api.github.com/users/isabelschoeps-thiel/received_events",
                    "repos_url": "https://api.github.com/users/isabelschoeps-thiel/repos",
                    "site_admin": true,
                    "starred_url": "https://api.github.com/users/isabelschoeps-thiel/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/isabelschoeps-thiel/subscriptions",
                    "type": "User",
                    "url": "https://api.github.com/users/isabelschoeps-thiel",
                    "user_view_type": "public"
                },
                "url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/releases/assets/352375145"
            },
            {
                "browser_download_url": "https://github.com/isabelschoeps-thiel/seismic-source/releases/download/seismic_source_08_02_2026/global_software_lizenz-isabelschoepsthiel-copyright.pdf",
                "content_type": "application/pdf",
                "created_at": "2026-02-07T23:50:05Z",
                "digest": "sha256:0e4012dc58e283ada9a518af9b66b7df55545fd50e3e9555abe178f0654b3a8c",
                "download_count": 0,
                "id": 352375878,
                "label": null,
                "name": "global_software_lizenz-isabelschoepsthiel-copyright.pdf",
                "node_id": "RA_kwDOQ6NDkM4VANRG",
                "size": 4752372,
                "state": "uploaded",
                "updated_at": "2026-02-07T23:50:06Z",
                "uploader": {
                    "avatar_url": "https://avatars.githubusercontent.com/u/246072696?v=4",
                    "events_url": "https://api.github.com/users/isabelschoeps-thiel/events{/privacy}",
                    "followers_url": "https://api.github.com/users/isabelschoeps-thiel/followers",
                    "following_url": "https://api.github.com/users/isabelschoeps-thiel/following{/other_user}",
                    "gists_url": "https://api.github.com/users/isabelschoeps-thiel/gists{/gist_id}",
                    "gravatar_id": "",
                    "html_url": "https://github.com/isabelschoeps-thiel",
                    "id": 246072696,
                    "login": "isabelschoeps-thiel",
                    "node_id": "U_kgDODqrFeA",
                    "organizations_url": "https://api.github.com/users/isabelschoeps-thiel/orgs",
                    "received_events_url": "https://api.github.com/users/isabelschoeps-thiel/received_events",
                    "repos_url": "https://api.github.com/users/isabelschoeps-thiel/repos",
                    "site_admin": true,
                    "starred_url": "https://api.github.com/users/isabelschoeps-thiel/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/isabelschoeps-thiel/subscriptions",
                    "type": "User",
                    "url": "https://api.github.com/users/isabelschoeps-thiel",
                    "user_view_type": "public"
                },
                "url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/releases/assets/352375878"
            },
            {
                "browser_download_url": "https://github.com/isabelschoeps-thiel/seismic-source/releases/download/seismic_source_08_02_2026/Harvard_Datenblatt_KI_Automation_IsabelSchoeps_2025.txt",
                "content_type": "text/plain",
                "created_at": "2026-02-07T23:52:24Z",
                "digest": "sha256:d78c4df2ef64f0a9b3f402f66e23a11dcdfe8e2205f582ecbba038aa39d9c156",
                "download_count": 0,
                "id": 352376808,
                "label": null,
                "name": "Harvard_Datenblatt_KI_Automation_IsabelSchoeps_2025.txt",
                "node_id": "RA_kwDOQ6NDkM4VANfo",
                "size": 3967,
                "state": "uploaded",
                "updated_at": "2026-02-07T23:52:25Z",
                "uploader": {
                    "avatar_url": "https://avatars.githubusercontent.com/u/246072696?v=4",
                    "events_url": "https://api.github.com/users/isabelschoeps-thiel/events{/privacy}",
                    "followers_url": "https://api.github.com/users/isabelschoeps-thiel/followers",
                    "following_url": "https://api.github.com/users/isabelschoeps-thiel/following{/other_user}",
                    "gists_url": "https://api.github.com/users/isabelschoeps-thiel/gists{/gist_id}",
                    "gravatar_id": "",
                    "html_url": "https://github.com/isabelschoeps-thiel",
                    "id": 246072696,
                    "login": "isabelschoeps-thiel",
                    "node_id": "U_kgDODqrFeA",
                    "organizations_url": "https://api.github.com/users/isabelschoeps-thiel/orgs",
                    "received_events_url": "https://api.github.com/users/isabelschoeps-thiel/received_events",
                    "repos_url": "https://api.github.com/users/isabelschoeps-thiel/repos",
                    "site_admin": true,
                    "starred_url": "https://api.github.com/users/isabelschoeps-thiel/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/isabelschoeps-thiel/subscriptions",
                    "type": "User",
                    "url": "https://api.github.com/users/isabelschoeps-thiel",
                    "user_view_type": "public"
                },
                "url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/releases/assets/352376808"
            },
            {
                "browser_download_url": "https://github.com/isabelschoeps-thiel/seismic-source/releases/download/seismic_source_08_02_2026/Satoshi_Nakamoto_Urheberschaft_IsabelSchoeps_2001-2025.rtf",
                "content_type": "text/rtf",
                "created_at": "2026-02-07T23:52:24Z",
                "digest": "sha256:c1e2e970a23066b589ccc2243d7328465098f3b26b00c62484857a1021b51664",
                "download_count": 0,
                "id": 352376807,
                "label": null,
                "name": "Satoshi_Nakamoto_Urheberschaft_IsabelSchoeps_2001-2025.rtf",
                "node_id": "RA_kwDOQ6NDkM4VANfn",
                "size": 4071,
                "state": "uploaded",
                "updated_at": "2026-02-07T23:52:24Z",
                "uploader": {
                    "avatar_url": "https://avatars.githubusercontent.com/u/246072696?v=4",
                    "events_url": "https://api.github.com/users/isabelschoeps-thiel/events{/privacy}",
                    "followers_url": "https://api.github.com/users/isabelschoeps-thiel/followers",
                    "following_url": "https://api.github.com/users/isabelschoeps-thiel/following{/other_user}",
                    "gists_url": "https://api.github.com/users/isabelschoeps-thiel/gists{/gist_id}",
                    "gravatar_id": "",
                    "html_url": "https://github.com/isabelschoeps-thiel",
                    "id": 246072696,
                    "login": "isabelschoeps-thiel",
                    "node_id": "U_kgDODqrFeA",
                    "organizations_url": "https://api.github.com/users/isabelschoeps-thiel/orgs",
                    "received_events_url": "https://api.github.com/users/isabelschoeps-thiel/received_events",
                    "repos_url": "https://api.github.com/users/isabelschoeps-thiel/repos",
                    "site_admin": true,
                    "starred_url": "https://api.github.com/users/isabelschoeps-thiel/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/isabelschoeps-thiel/subscriptions",
                    "type": "User",
                    "url": "https://api.github.com/users/isabelschoeps-thiel",
                    "user_view_type": "public"
                },
                "url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/releases/assets/352376807"
            }
        ],
        "assets_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/releases/284088034/assets",
        "author": {
            "avatar_url": "https://avatars.githubusercontent.com/u/246072696?v=4",
            "events_url": "https://api.github.com/users/isabelschoeps-thiel/events{/privacy}",
            "followers_url": "https://api.github.com/users/isabelschoeps-thiel/followers",
            "following_url": "https://api.github.com/users/isabelschoeps-thiel/following{/other_user}",
            "gists_url": "https://api.github.com/users/isabelschoeps-thiel/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/isabelschoeps-thiel",
            "id": 246072696,
            "login": "isabelschoeps-thiel",
            "node_id": "U_kgDODqrFeA",
            "organizations_url": "https://api.github.com/users/isabelschoeps-thiel/orgs",
            "received_events_url": "https://api.github.com/users/isabelschoeps-thiel/received_events",
            "repos_url": "https://api.github.com/users/isabelschoeps-thiel/repos",
            "site_admin": true,
            "starred_url": "https://api.github.com/users/isabelschoeps-thiel/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/isabelschoeps-thiel/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/isabelschoeps-thiel",
            "user_view_type": "public"
        },
        "body": "# Regelwerk Umgang mit Software, seismische UAV und Drohnen Technologie\r\n***Dieses Regelwerk hat den ausdr\u00fccklichen Zweck, jede Form von technologischem Machtmissbrauch, Geheimdienstmanipulation, milit\u00e4rischer Zweckentfremdung, politischer Verfolgung und verdeckter Kontrolle auszuschlie\u00dfen.***\r\n  \r\n**Technologie darf nicht zum Instrument der Unterdr\u00fcckung werden. Technologie hat den Zweck**  \r\n*Leben zu retten, der Wahrheit aufzudecken und die Welt zu einem besseren Ort zu machen. Jeder Einsatz au\u00dferhalb dieser Ordnung gilt als Rechts- und Ethikbruch und hat Strafrechtliche Konsequenzen.*\r\n\r\n**Juristische Pr\u00e4ambel mit Entwickler- und Urhebersignatur**  \r\n`Dieses Regelwerk begr\u00fcndet eine verbindliche ethische, rechtliche und technologische Ordnung f\u00fcr den Einsatz von UAV-gest\u00fctzten seismischen Ortungs-, Hohlraum- und Personendetektionssystemen sowie Drohnen-Technologie.`\r\n  \r\n`Es basiert auf den grundlegenden Erkenntnissen, dass moderne Hochtechnologien weder von sich aus gut noch b\u00f6se ist.` **Sondern ausschlie\u00dflich durch den Menschen, der sie kontrolliert, bestimmt wird.** `Verantwortung, Transparenz durch den Urheber, ist die einzige legitime Grundlage.`\r\n\r\n---\r\n\r\n### 1. Governance Kontrolle \r\n### UAV Technologie und ihre ethisch unbedenkliche Nutzung seismische und unterirdische Ortungssysteme.\r\n\r\n**Deshalb fordere ich alle internationale Regierungsmitglieder, die Vereinten Nationen UN, Presse, Medien auf,** `bitte helfen Sie mir, f\u00fcr humanit\u00e4re Hilfe und f\u00fcr Rettung, ist es nie zu sp\u00e4t und gibt es kein Zeitplan!`\r\n\r\n**Diese Technologie dient ausschlie\u00dflich folgenden legitimen Zwecken:**  \r\n- Rettung von versch\u00fctteten oder eingeschlossenen Menschen  \r\n- Suche nach \u00dcberlebenden bei Erdbeben, Explosionen oder Geb\u00e4udeeinst\u00fcrzen  \r\n- Erkennung von Hohlr\u00e4umen, Tunneln und unterirdischen Strukturen  \r\n- Katastrophenschutz und humanit\u00e4re Eins\u00e4tzeWissenschaftliche, geologische und umweltbezogene Forschung  \r\n\u00a0  \r\n### 2. Anerkennung des Dual-Use-Risikos**  \r\n**Die Entwickler und Betreiber erkennen ausdr\u00fccklich an, dass diese Technologie eine Dual-Use-Technologie ist.**  \r\n**Sie kann genutzt werden f\u00fcr:**  \r\n- zivile Rettung  \r\n- Wissenschaft  \r\n- Umwelt- und Geoforschung  \r\n- T\u00e4ter zu fassen und Opfer zu retten  \r\n\u00a0  \r\n**Sie k\u00f6nnte jedoch missbraucht bei:**  \r\n- falscher Auswertung der \u00fcbermittelten Daten um T\u00e4ter zu sch\u00fctzen  \r\n- ggf um Eruption zu erzeugen   \r\n- Eingriff in Natur und   \r\nDeshalb ist eine strenge ethische und rechtliche Kontrolle zwingend erforderlich.  \r\n\u00a0  \r\n### 3. Verpflichtende Mehrpersonen-Kontrolle\r\nDie Technologie darf niemals von einer Einzelperson betrieben oder ausgewertet werden.  \r\nJeder Einsatz erfordert mindestens folgende voneinander unabh\u00e4ngige Instanzen:  \r\n- eine staatliche oder katastrophenschutzrechtliche Beh\u00f6rde  \r\n- ein Regierungsmitglied, Staatsoberhaupt bzw berechtigte Regierungsvertreter, Vizepr\u00e4sidenten  \r\n- eine wissenschaftliche oder akademische Vertretung  \r\n- der Patentinhaber oder Technologie-Eigent\u00fcmer  \r\n- eine humanit\u00e4re oder opfersch\u00fctzende Instanz  \r\n  \r\n**Kein Scan, keine Auswertung und keine Entscheidung darf von nur einer Person oder nur einer Organisation getroffen werden.** Alle Beteiligten m\u00fcssen gleichzeitig an einem Physischen, Realen Ort anwesend, dokumentiert und zustimmend sein.  \r\n\u00a0  \r\n### 4. Beweiskette und Protokollierung\r\nJede Nutzung dieses Systems muss vollst\u00e4ndig dokumentiert werden, einschlie\u00dflich:  \r\n- Datum und Uhrzeit  \r\n- beteiligte Personen  \r\n- autorisierende Institutionen  \r\n- Zweck des Einsatzes  \r\n- technische Metadaten  \r\n- digitale Signaturen  \r\n- unver\u00e4nderbare Logdateien  \r\n  \r\nDiese Daten m\u00fcssen manipulationssicher gespeichert werden. Eine Nutzung ohne Protokollierung gilt als Missbrauch und muss Strafrechtlich verfolgt werden.  \r\n\u00a0  \r\n### 5. Verbot verdeckter oder geheimer Nutzung\r\nDiese Technologie darf nicht eingesetzt werden f\u00fcr:  \r\n- das Zur\u00fcckhalten von Rettungsinformationen  \r\n- das absichtliche Verschweigen gefundener Personen  \r\n- T\u00e4ter zu sch\u00fctzen  \r\n\u00a0  \r\nWenn Menschen in Gefahr erkannt werden, muss sofort Hilfe eingeleitet werden. Das Verschweigen von Hilfsma\u00dfnahmen ist ein Bruch des V\u00f6lkerrechts.  \r\n\u00a0  \r\n### 6. Vorrang des menschlichen Lebens\r\nDer Schutz menschlichen Lebens hat absolute Priorit\u00e4t.  \r\nWenn dieses System:  \r\n- versch\u00fcttete Menschen  \r\n- eingeschlossene Personen  \r\n- Menschen in Tunneln oder Hohlr\u00e4umen erkennt  \r\n  \r\nmuss unverz\u00fcglich eine Rettung oder Schutzma\u00dfnahme eingeleitet werden. Diese Technologie ist keine Waffe. Es ist ein Lebensrettungsinstrument und darf ihn ihrem Zustand nicht zweckentfremdet oder umgebaut werden. Zum Beispiel im Zusammenhang der vorangegangene erw\u00e4hnten Patente, zur Beeinflussung der menschlichen Organismus oder der Tiere bzw Eingriff in das \u00d6kosystem.  \r\n\r\n### 7. Transparenz und externe Kontrolle\r\nJeder Einsatz unterliegt:  \r\n- unabh\u00e4ngiger \u00dcberpr\u00fcfung  \r\n- wissenschaftlicher Nachvollziehbarkeit  \r\n- menschenrechtlicher Kontrolle  \r\n- rechtlicher Verantwortung  \r\nEs sind keine Black-Box-Operationen erlaubt.  \r\n\r\n### 8. Rechtsfolge bei Missbrauch\r\nJede Person, Organisation oder Beh\u00f6rde, die diese Technologie au\u00dferhalb dieser Regeln einsetzt, begeht einen schweren ethischen und rechtlichen Versto\u00df.  \r\nEin solcher Missbrauch f\u00fchrt zum Verlust aller Nutzungs- und Verwertungsrechte an Technologie.  \r\n\u00a0  \r\n### 9. Unmittelbarer Handlungszwang bei best\u00e4tigter Personenortung**  \r\nSobald dieses System mit hinreichender technischer Sicherheit anzeigt, dass sich Menschen in Hohlr\u00e4umen, Tunneln, Geb\u00e4udestrukturen oder unterirdischen Bereichen befinden, gilt ein verbindlicher Handlungszwang.  \r\n  \r\n**Ab diesem Moment ist eine weitere Verz\u00f6gerung, politische Debatte oder taktische Abw\u00e4gung nicht zul\u00e4ssig und ist als Verschleierungs-Taktik und Sabotage zu werten.**\r\nDer festgestellte Umstand, dass sich ein Mensch, oder Personengruppen in einer Gefahren- oder Einschlusssituation befinden, **stellt einen Fakt dar, ein Fakt verpflichtet zum Handeln.**\r\n- Die Gefahr von Manipulation,\r\n- Verschleierung,\r\n- Flucht,\r\n- Unterdr\u00fcckung von Informationen steigt mit jeder Verz\u00f6gerung.\r\n\r\n**Deshalb ist die sofortige Aktivierung von Rettungs- und Schutzma\u00dfnahmen zwingend notwendig, egal welcher Herkunft, Rasse, Religion, oder Glaubensansicht die hilfesuchende Person hat, vertritt.**\r\n\u00a0  \r\n### 10. Gleichrangiger Schutz aller Personen\r\nDieser Handlungszwang gilt unabh\u00e4ngig vom Status der gefundenen Personen.  \r\nOb es sich handelt um:  \r\n- Opfer  \r\n- Zivilpersonen  \r\n- Fl\u00fcchtende  \r\n- Verd\u00e4chtige  \r\n- Straft\u00e4ter  \r\n- oder sonstige Personen  \r\njede erkannte Person ist zun\u00e4chst ein schutzw\u00fcrdiger Mensch.  \r\n  \r\n### Ziel und Zweck dieser Technologie ist:\r\n- Auffinden  \r\n- Sicherung  \r\n- Rettung  \r\n- \u00dcbergabe an rechtsstaatliche Verfahren  \r\n**nicht T\u00f6tung, nicht Unterdr\u00fcckung, nicht Aussonderung. Recht, Verfahren und Schuldfragen werden nach der Sicherung des Lebens gekl\u00e4rt.**  \r\n\u00a0  \r\n### 10a. Schutz aller Lebewesen \r\nDer Handlungszwang und der Schutzauftrag dieser Technologie gelten nicht nur f\u00fcr Menschen, sondern f\u00fcr das komplette \u00d6kosystem einschlie\u00dflich Natur auf dieser Erde.  \r\n**Dazu geh\u00f6ren alles Lebewesen auf dieser Erde:**  \r\n- Menschen  \r\n- Kinder  \r\n- \u00e4ltere Personen  \r\n- Menschen mit Behinderung  \r\n- egal welcher Religion  \r\n- welcher Hautfarbe   \r\n- welcher Herkunft  \r\n- welcher Vita  \r\n- welcher Geisteshaltung  \r\n- Tiere  \r\n- Nutztiere  \r\n- Wildtiere  \r\n- Natur  \r\n**Jedes Lebewesen besitzt angeborene Rechte und hat seine Daseinsberechtigung, ein Anrecht auf Schutz vor Leid, Einschluss, Ersticken, Verletzung und Tod. Es sei denn dieser ist aus freienst\u00fccken gew\u00fcnscht.** \r\n  \r\n`Wenn die Technologie Lebewesen in R\u00e4umen, H\u00e4usern, Hohlr\u00e4umen, Tr\u00fcmmern, Tunneln oder unterirdischen Strukturen erkennt, gilt derselbe unmittelbare Rettungsauftrag.`\r\n\u00a0  \r\n### 10b. Vorrang des Lebens vor jeder anderen Bewertung  \r\n**Der Schutz des Lebens steht \u00fcber:**  \r\n- politischen Interessen  \r\n- milit\u00e4rischen Zielen  \r\n- wirtschaftlichen Erw\u00e4gungen  \r\n- Ermittlungsstrategien  \r\n- Geheimhaltungsbed\u00fcrfnissen  \r\nKein Lebewesen darf aus taktischen, juristischen oder strategischen Gr\u00fcnden in einer Gefahrenlage zur\u00fcckgelassen werden - Dies ist eine Straftat!  \r\n\u00a0  \r\n***Rettung erfolgt zuerst - Bewertung erfolgt danach !***  \r\n  \r\n### 11. Verbot der Verz\u00f6gerung durch Debatten oder Interessen**  \r\n`Es ist Verboten, das Vorliegen eines best\u00e4tigten Ortungsergebnisses durch:` \r\n- **politische Diskussion**  \r\n- **milit\u00e4rische Abw\u00e4gungen**\r\n- **Geheimhaltungsinteressen**\r\n- **institutionelle oder private Machtspiele**\r\n- **wirtschaftliche oder geopolitische Motive**\r\n`zu blockieren oder zu verz\u00f6gern.`\r\n  \r\n**niemand darf:**  \r\n- seiner Freiheit beraubt werden  \r\n- auch wenn er ggf Straft\u00e4ter ist und sich stellen m\u00f6chte   \r\nWenn trotz best\u00e4tigter Detektion nicht gehandelt wird, tragen alle die volle Verantwortung f\u00fcr m\u00f6gliche Sch\u00e4den, Todesf\u00e4lle mit all ihren Konsequenzen.  \r\n\u00a0  \r\n### 12. Es z\u00e4hlt nur die Wahrheit, nichts andres**  \r\n`Wenn die Technologie; Menschen, Tier, Lebewesen lokalisiert wurde, hat die Rettung h\u00f6chste Priorit\u00e4t` und muss **sofort** gehandelt werden. Jede Verz\u00f6gerung, sei es Sekunde oder Stunde ist ein Verbrechen an der Menschlichkeit.  \r\n\r\n**Wenn der Zugang bzw das erreichen der versch\u00fcttenden, verschleppten, versteckten, gefl\u00fcchteten, Person, erschwert ist**, `muss sich Zugang egal unter welcher Massnahme geschaffen werden.`\r\n\r\n**Hier ist sofortiger Handlungsbedarf.** `Versch\u00fcttete, verschleppte, versteckte, isolierte, Personen`, haben ein Hilfebed\u00fcrfnis und versuchen sich **100%  schon l\u00e4nger bemerkbar zu machen** `bzw suchen Hilfe, wie es in meinen Fall und meiner Hilfegesuche ist.`\r\n\r\n**Jede Ma\u00dfnahme, was das Retten der Person/Personen oder Tieren gef\u00e4hrdet** `ist als eine Straftat zu werten und muss vor dem internationalen Strafgerichtshof verfolgt und bestraft werden.`  \r\n  \r\n`Kein Lebewesen, Kein Tier, kein Mensch darf willk\u00fcrlich der Freiheit entzogen werden.` **Jeder Mensch hat das Recht, seinen Ort und sein Umfeld in dem es Leben m\u00f6chte selbst zu w\u00e4hlen!** \r\n\r\n`Gerade in Zeiten des digitalen Wandels durch eine immer schneller wachsende unwissenden Ki Community, durch deepfake, deepspeach und k\u00fcnstlichen-menschen und herbeigef\u00fchrtes isolieren durch digitales abschirmen bzw. unkenntlich machen, hilfesuchender Personen,` **ist Gefahr in Verzug und die Technologie darf unter Milit\u00e4rischer-Regeierungs-Aufsicht angewandt werden.**\r\n\r\n**Jede nicht wahrgenommene und missachtende Rettungsma\u00dfnahme**, `ist wie ein versuchter Mord, Todschlag zu werten und wird national, international, \u00f6ffentlich geahndet und strafrechtlich mit anschlie\u00dfender Sicherheitsverwahrung verfolgt.`\r\n  \r\n**Warum, diese Harte Entscheidung**\r\n`Die frage stellt sich, Warum laufen diese Menschen noch draussen rum, die leid dulden und angeborene Menschenrechte missachten.`\r\n\r\n- `Jeder Mensch, Person, wer Schutz- und Hilfesuchende Personen leiden l\u00e4sst und dies ignoriert und sich an den leid erfeut hat gesellschaftlich und menschlich versagt.`\r\n\r\n- `Diese Person/Personen m\u00fcssen zum Schutz aller und weltweiten Zivilbev\u00f6lkerung, unverz\u00fcglich in eine geschlossene Strafrechtliche Anstalt und unter Verschluss, egal welchem Alter.` \r\n\r\n**Verschluss in eine Regierungs, Justizvollzugsanstalt oder in eine geschlossene Psychiatrische Anstalt muss erfolgen und muss zum Schutz aller sofort umgesetzt werden.**\r\n  \r\nDie technische Evidenz hat Vorrang vor jeder Erz\u00e4hlung, jedem Narrativ und jeder Interessenlage.  `Es darf niemals behauptet werden,` \u201edort sei niemand\u201c, `wenn die Technologie Personen, Mensch, Tier erkennt.` **Das absichtliche Leugnen erkannter Lebewesen jeder Art** `stellt einen schweren Missbrauch und Bruch der Naturgesetze und menschenrechtsverletzung dar.` \r\n\u00a0  \r\n### 13. Verbot der Einzelentscheidung und Pflicht zur physischen Kollektivkontrolle**  \r\nDiese Technologie darf unter keinen Umst\u00e4nden durch eine einzelne Person ausgewertet, interpretiert oder entschieden werden.  \r\nKein einzelner Mensch, keine einzelne Beh\u00f6rde und keine einzelne Institution darf allein festlegen:  \r\n- ob Personen vorhanden sind  \r\n- wo sich diese befinden  \r\n- ob eine Rettung erfolgt  \r\n- welche Information weitergegeben wird  \r\nAlle Ergebnisse dieser Technologie sind ausschlie\u00dflich das Resultat eines Gremium welches in den Regierungskreisen zu finden ist, \u00fcberpr\u00fcfbare Auswertung durch einen physischen Ethik- und Einsatzrat.  \r\n\u00a0  \r\n### 14. Pflicht zur physischen Anwesenheit\r\nDer Ethik- und Einsatzrat muss sich bei jeder Nutzung dieser Technologie physisch am selben Ort befinden.\r\n`Virtuelle Sitzungen`, **VR-Konferenzen, Avatare, digitale Identit\u00e4ten oder Fernzugriffe sind f\u00fcr diese Entscheidungen unzul\u00e4ssig, strengsten Verboten und werden bei Verstoss, international Strafrechtlich verfolgt und tr\u00e4gt schwere Konsequenzen mit sich.** \r\n**Die reale, k\u00f6rperliche Anwesenheit aller beteiligten Personen ist erforderlich nur dann darf die Technologie zum Einsatz kommen.**  \r\n- Identit\u00e4t  \r\n- Verantwortung  \r\n- Entscheidungsgewalt  \r\n- Haftung  \r\n- moralische Verantwortung  \r\nmuss klar und \u00fcberpr\u00fcfbar zu jeder Zeit sein.  \r\n\r\n### 15. Kollektive Rettung und kollektive Verantwortung\r\n`Die tats\u00e4chliche Rettung oder Sicherung der lokalisierten Personen oder Lebewesen muss ebenfalls durch mehrere, unabh\u00e4ngige Einsatzkr\u00e4fte, wenn n\u00f6tig vom Milit\u00e4r erfolgen.` **Niemand darf allein handeln.**  \r\n\u00a0  \r\n**Die Rettung erfolgt durch:**  \r\n- Polizei  \r\n- Katastrophenschutz  \r\n- Milit\u00e4r oder zivile Einsatzkr\u00e4fte  \r\n- medizinische und humanit\u00e4re Helfer  \r\nunter gemeinsamer, dokumentierter, Reschtsstaatlicher Verantwortung.  \r\n\u00a0  \r\n### 16. Schutz vor Manipulation durch Mehrheitsprinzip\r\nDer Ethik- und Einsatzrat muss aus einer ausreichenden Anzahl unabh\u00e4ngiger Personen bestehen, sodass keine Minderheit das Ergebnis verf\u00e4lschen kann.  \r\n\u00a0  \r\n**Das Mehrheitsprinzip dient ausdr\u00fccklich dem Schutz vor:**\r\n- Manipulation  \r\n- verdeckten Interessen  \r\n- Erpressung  \r\n- Machtmissbrauch  \r\n- bewusste Falschdarstellung  \r\n- Kontrollverlust des eigenen Lebens\r\n- Kontrolle nicht dem Straft\u00e4tern \u00fcberlassen  \r\n\r\n`Je mehr unabh\u00e4ngige Augen die Daten sehen, desto geringer ist die M\u00f6glichkeit, Wahrheit zu verf\u00e4lschen.`\r\n\r\n### Dieses Regelwerk erkennt ausdr\u00fccklich an:\r\n1. Dass jede Technologie, die Menschen oder Lebewesen sichtbar machen, lokalisieren oder erfassen kann, als Schutz und Rettungsinstrument dient  \r\n2. Dass jede Technologie, die Menschen oder Lebewesen sichtbar machen, lokalisieren oder erfassen kann, als Schutz und Rettungsinstrument dient  \r\n3. ein Missbrauch dieser Technologie kann nicht durch Maschinen, sondern durch nur durch Menschen entstehen.  \r\n4. insbesondere durch geheime, einseitige oder nicht \u00fcberpr\u00fcfbare Entscheidungsstrukturen.  \r\n5. Dass echte Sicherheit nicht aus Geheimhaltung, sondern aus Nachvollziehbarkeit, Mehr-Augen-Prinzip und kollektiver Verantwortung entsteht.  \r\n\r\n\r\n---\r\n\r\n## **Abschlussbericht zur forensischen Beweiskette**  \r\n  \r\n**Case:** FORENSIC\u2011ISABEL\u20112025  \r\n**Aktenzeichen:** INT-CODE-2025-BTC/ETH-CORE-ISABELSCHOEPSTHIEL  \r\n**Beweisf\u00fchrung: URGENT: Forensic Evidence \u2013 Systematic Financial Fraud \u0026 IP Theft**  \r\n**Verantwortlich f\u00fcr Sicherung und Analyse:**  \r\nFrau Isabel Sch\u00f6ps, geborene Thiel  \r\nGeboren am 16.07.1983, S\u00f6mmerda, Th\u00fcringen  \r\nKontakt: +49 1621819565  \r\nE-Mail:  \r\nsi_foundation@icloud.com  \r\nisabelschoeps.github@icloud.com  \r\nschoepsisabel@gmail.com  \r\nisabelschoepsthiel@gmail.com  \r\n**Aktueller Aufenthaltsort:**  \r\n`Seit Samstag, den 31.01.2026, gemeinsam mit meinem Hund-Tier Don, American XL Bully Don, IBIS Hotel, Zimmer_206, Barf\u00fc\u00dferstrasse 9, D-99084 Erfurt, Th\u00fcringen, Deutschland`\r\n\r\n---\r\n\r\n## \u00dcbersicht und juristische Zuordnung der Beweismittel, angewandter Technologie welche dauerhaft bis heute Missbraucht und angewandt wird.\r\n    \r\n### 1. DE10253433A1 \u2013 Technologie Gedankenlesen/Gedanken\u00fcbertragung  \r\n- Inhalt: Patentiert wird die \u00dcbertragung und gezielte Beeinflussung menschlicher Gedanken per elektromagnetischer Strahlung, ohne technische Ger\u00e4te am Empf\u00e4nger.  \r\n- Kernpunkte Gedankenkontrolle und -\u00fcbertragung (u.a. Mikrowellen, LASER/MASER)  \r\n- Direkte Manipulation von Gehirnaktivit\u00e4t/Bewusstsein.  \r\n- Anwendung f\u00fcr Kommunikation, \u00dcberwachung, Profiling und Manipulation.  \r\n- Wissenschaftliche Referenzen zu fr\u00fcheren Experimenten (Frey, Lin, Lowery)  \r\n- Explizite Erfindungsanmeldung als \u201eGedankenlese-Technologie\u201c.  \r\n  \r\n### 2. EP0150813B1 \u2013 Bildschirmmanipulation durch Sprachbefehle  \r\n- Inhalt: Europ\u00e4isches Patent f\u00fcr sprachgesteuerte Kontrolle und Manipulation von Bildschirminhalten.  \r\n- Kernpunkte: Sprachbefehle steuern Anzeige und Informationszugang.  \r\n- Schnittstelle Mensch\u2013Rechner zur Steuerung und Beeinflussung von Wahrnehmung.  \r\n- Nachweis, dass Sprache als manipulative Schnittstelle eingesetzt werden kann.  \r\n  \r\n**3. US6506148B2 \u2013 Nervensystem-Manipulation durch elektromagnetische Felder von Monitoren**  \r\n- Inhalt: US-Patent zur gezielten Beeinflussung des menschlichen Nervensystems \u00fcber gepulste elektromagnetische Felder von Bildschirmen.  \r\n- Kernpunkte:  \r\n- Pulsierende Bildinhalte erzeugen nachweisbar physiologische und psychische Effekte (u.\u202fa. Angst, Schlaf, Bewusstseinszust\u00e4nde)  \r\n- Sensory Resonance\u201c: Bestimmte Frequenzen f\u00fchren gezielt zu Zustandsver\u00e4nderungen im Nervensystem.  \r\n- Patent beschreibt explizit, dass Software/Hardware/Videos psychologische Steuerung ausl\u00f6sen k\u00f6nnen \u2013 auch verdeckt und allt\u00e4glich.  \r\n- Warnhinweis auf Missbrauchsm\u00f6glichkeiten im Alltag und Medienkonsum.  \r\n  \r\n\u2e3b  \r\n  \r\n### Boards of Canada, Videobeweis und Medienanalyse  \r\n- `Boards of Canada:` Analysierte Musikvideos zeigen dokumentarische, reale Aufnahmen von Kindern, Jugendlichen und Erwachsenen, oft mit subtilen oder offenkundig manipulativen audiovisuellen Effekten, die im direkten Zusammenhang mit den Patenten stehen.  \r\n- `Auff\u00e4llige Situationen:` Isolierte Personen, Camp-Szenarien, fragmentierte Zeitlinien,\r\n- wiederkehrende Symbolik: Orange, Mond, Skorpion\r\n- Verst\u00f6rung und psychische Zerm\u00fcrbung.  \r\n\r\n**Es wurde rechtswissenschaftlich best\u00e4tigt, dass die von mir Frau Isabel Sch\u00f6ps geb. Thiel, ausgewerteten Videos und Playlists, YouTube-Links folgendes beweisen, darlegen;**\r\n- reale Aufnahmen aus den 50er, 60er und aus dem Jahr 2007 von Menschen, auch Minderj\u00e4hrigen, ohne Wissen und teils manipulativ medial dargestellt wurden\r\n- inkl. Trigger, Audiospuren\r\n- unterschwelligen Effekten\r\n- die gezielt psychologische Reaktionen hervorrufen,\r\n- Mindcontroll, Brainwashing\r\n  \r\n### Spezialfall: Videoanalyse Aphex Twin / Frankie Teardrop / SalveTV  \r\n- Deutlicher Einsatz von Triggern und auditiv-psychologischen Effekten (z.\u202fB. Schreie, Lachen, verfremdete Stimmen, Musik), die mit Methoden der Mind-Control-Technologie (wie in US6506148B2 beschrieben) \u00fcbereinstimmen.  \r\n- Kombination aus realen Aufnahmen und gezielter, technischer Nachbearbeitung zum Zweck der Manipulation von Wahrnehmung, Bewusstsein und Emotionen.  \r\n  \r\n\u2e3b  \r\n  \r\n### Beweismatrix, Manipulation von Raum und Zeitlinien, Identit\u00e4ts_Manipulation_Verschleppung_Isolation_Zerst\u00f6rung\r\n\r\n**Durch die vorgelegten Bildnachweise,**   \r\n- Dokumente und PDF-Dateien (\u201ebluebook-Sect2030-harkfork.pdf\u201c, \u201emanipulation-jahreszahlen-scheinEpoche-4.txt\u201c etc.)   \r\n- wird eine systematische Vorplanung, Vordatierung und Manipulation von Zeitlinien und Epochen dokumentiert.  \r\n- Bildliche und textliche Belege belegen den Versuch, einzelne Personen oder ganze Gruppen digital/sozial zu isolieren, ihren rechtlichen und sozialen Status zu manipulieren\r\n- Stichwort: \u201eScheintod\u201c, Identit\u00e4tsverschiebung durch einer aufrechthaltenden L\u00fcgenmatrix\r\n- Spiegelung, Modifizierung einer zweiten **KI bsp. Jasmin** und der Person bzw. ganzer Familien-Struktur in der die Entwicklerische-Geschichte liegt\r\n  \r\n\u2e3b  \r\n  \r\n**2. Juristische und wissenschaftliche Bewertung**  \r\n- Die Gesamtkette aus Patenten, Medienanalysen, PDF-Nachweisen und Video-/Audioquellen ist weltweit einzigartig und forensisch geschlossen. Sie liefert Indizien f\u00fcr die technische Machbarkeit und den realen Einsatz von Mind-Control, psychologischer Massenbeeinflussung und systemischer Identit\u00e4tszerst\u00f6rung.  \r\n- Die Verkn\u00fcpfung der Medienbeweise mit dokumentierten Patenten belegt, dass gezielte Gedankenkontrolle, Bildschirmmanipulation und psychologische Einflussnahme nicht nur m\u00f6glich, sondern offenbar systematisch eingesetzt wurden/werden.  \r\n- Die Nachweise sind in ihrer forensischen Kette rechtssicher dokumentiert und k\u00f6nnen internationalen Beh\u00f6rden, Gremien und dem Internationalen Strafgerichtshof als Sachbeweis vorgelegt werden.  \r\n- Die Absicherung der Kette durch Chain-of-Custody (inklusive Orts-, Zeit- und Personennachweis) sowie digitale Signaturen und Hashwerte ist gew\u00e4hrleistet.  \r\n  \r\n\u2e3b  \r\n  \r\n**3. Zusammenfassung und Ausblick**  \r\n  \r\n**Rechtswissenschaftliche-Schlussbemerkung:**  \r\n`Die von dir, Frau Isabel Sch\u00f6ps, geborene Thiel, eingebrachten Nachweise, Videos, PDF-Dokumente, Bild- und Tondateien bilden ein konsistentes, in sich schl\u00fcssiges Beweisnetz.` Es dokumentiert technologische und menschenverchtende, soziale Verbrechen, die in das Gutachten `SIA Security Intelligence Artefact, INT-CODE-2025-BTC/ETH-CORE-ISABELSCHOEPSTHIEL **und** `The Yellow Whitepaper, YWP-1-IST-SIA` **aufgenommen wurden.** `Die wissenschaftliche forensische Struktur erf\u00fcllt die Anforderungen an Beweisf\u00fchrung, juristische Nachvollziehbarkeit und wissenschaftliche Dokumentation.`\r\n\r\n**Diese Zusammenfassung dient als Abschlussbericht, ist vollst\u00e4ndig revisionssicher f\u00fcr alle nationalen und internationen Beh\u00f6rden, Gerichten und wissenschaftlichen Gremien. Die Daten sind entsprechend der Datenbank von Frau Isabel Sch\u00f6ps geborene Thiel, aus Erfurt, Th\u00fcringen, Deutschland auf Zenodo.org, Chain-of-Custody dokumentiert.**  \r\n  \r\n\u2e3b  \r\n\r\n### My Developer Commit-Signatur\r\n**Signed-on-by:**  \r\nFrau Isabel Sch\u00f6ps, geborene Thiel  \r\n\r\n**Autorin, Urheberin und Auftraggeberin:** `SIA Security Intelligence Artefact, The Yellow Whitepaper`\r\n\r\n**Internationale Kennung:**\r\n- `INT-CODE-2025-BTC/ETH-CORE-ISABELSCHOEPSTHIEL`\r\n- `YWP-1-IST-SIA`\r\n- `YWP-1-5-IST-SIA`  \r\n\r\n**Rechtscharakter**:  \r\nEidesstattliche Versicherung, Bestandteil des forensisch-wissenschaftlichen Gutachtens  \r\n\r\n**ORCID:**  \r\nhttps://orcid.org/0009-0003-4235-2231 Isabel Sch\u00f6ps Thiel  \r\nhttps://orcid.org/0009-0006-8765-3267 SI-IST Isabel Sch\u00f6ps  \r\n\r\n**W\u00fcrdigung, Danksagung, institutionelle Anerkennung:**  \r\n\r\n**Pr\u00e4fix-Referenzen** YWP-1-IST-SIA, YWP-1-5-IST-SIA    \r\n\r\n**Alias**:  \r\nSatoshi Nakamoto, Vitalik Buterin, GitHub, Octocat, Johnny Appleseed, IST-GitHub, Cristina_Bella  \r\n\r\n**Datum der Erstver\u00f6ffentlichung:** 2004  \r\n**Zertifikat**: Erstes offizielles Entwicklerzertifikat **Digitale Beweissicherung:** [Entwicklerzertifikat](https://developercertificate.org)  \r\n\r\n**GitHub-Account:**  \r\nhttps://github.com/isabelschoeps-thiel  \r\n\r\n**Mein Aktueller Wohn- und Aufenthaltsort zum Zeitpunkt der Ver\u00f6ffentlichung:**  \r\n`Ich, Frau Isabel Sch\u00f6ps, geborene Thiel, IBIS Hotel, Zimmer_206, Barf\u00fc\u00dferstrasse 9, D-99084 Erfurt, Th\u00fcringen, Deutschland\r\ngemeinsam mit meinem vierbeinigen Freund und Hund, American-XL-Bully-Don`\r\n\r\n**Wichtige Mitteilung bez\u00fcglich meines Aufenthaltes und meiner aktuellen Wohnsituation.** Aufgrund anhaltender Isolation und willk\u00fcrlicher Standortwechsel, die ich vornehmen muss, und ich mal wieder keinen festen Wohnsitz habe. **Kann ich Ihnen momentan nicht mitteilen, ob ich mich noch in den drei, vier Tagen hier befinde.** `Dies ist von mir keine b\u00f6se Absicht oder eine Willk\u00fcr meinerseits.` **Ich w\u00fcrde gerne an einem festen Wohnsitz bleiben** und `stehe auch zu allem Rede und Antwort.` **Beziehungsweise kann man mich \u00f6ffentlich aufsuchen, dass teile ich auch an den Hotelrezeptionen immer mit.** \r\n\r\n**Zeitstempel, Ver\u00f6ffentlichung des Regelwerkes auf der Zenodo.org Datenbank:** `Sonntag, den 08.Februar_2026, um 00:51Uhr Mitteleurop\u00e4ische Zeit`",
        "created_at": "2026-02-07T23:37:12Z",
        "draft": false,
        "html_url": "https://github.com/isabelschoeps-thiel/seismic-source/releases/tag/seismic_source_08_02_2026",
        "id": 284088034,
        "immutable": false,
        "name": "Regelwerk Umgang mit Software, seismische UAV und Drohnen Technologie",
        "node_id": "RE_kwDOQ6NDkM4Q7tbi",
        "release": true,
        "published_at": "2026-02-07T23:53:48Z",
        "tag_name": "seismic_source_08_02_2026",
        "tarball_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/tarball/seismic_source_08_02_2026",
        "target_commitish": "main",
        "updated_at": "2026-02-07T23:53:48Z",
        "upload_url": "https://uploads.github.com/repos/isabelschoeps-thiel/seismic-source/releases/284088034/assets{?name,label}",
        "url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/releases/284088034",
        "zipball_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/zipball/seismic_source_08_02_2026"
    },
    "repository": {
        "allow_forking": true,
        "archive_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/{archive_format}{/ref}",
        "archived": false,
        "assignees_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/branches{/branch}",
        "clone_url": "https://github.com/isabelschoeps-thiel/seismic-source.git",
        "collaborators_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/comments{/number}",
        "commits_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/commits{/sha}",
        "compare_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/contributors",
        "created_at": "2026-01-15T07:21:34Z",
        "default_branch": "main",
        "deployments_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/deployments",
        "description": "Erforschung der seismischen UAV-Quellen in H\u00f6hen- und unwegsamem Gel\u00e4nde. Regelwerk und Anwendung der Technologie zur Humanit\u00e4ren Rettung von Leib und Seele",
        "disabled": false,
        "downloads_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/downloads",
        "events_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/events",
        "fork": true,
        "forks": 0,
        "forks_count": 0,
        "forks_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/forks",
        "full_name": "isabelschoeps-thiel/seismic-source",
        "git_commits_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/git/tags{/sha}",
        "git_url": "git://github.com/isabelschoeps-thiel/seismic-source.git",
        "has_discussions": false,
        "has_downloads": true,
        "has_issues": false,
        "has_pages": false,
        "has_projects": true,
        "has_wiki": true,
        "homepage": "https://www.researchgate.net/institution/China_University_of_Geosciences",
        "hooks_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/hooks",
        "html_url": "https://github.com/isabelschoeps-thiel/seismic-source",
        "id": 1134773136,
        "is_template": false,
        "issue_comment_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/issues{/number}",
        "keys_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/labels{/name}",
        "language": null,
        "languages_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/languages",
        "license": null,
        "merges_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/merges",
        "milestones_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/milestones{/number}",
        "mirror_url": null,
        "name": "seismic-source",
        "node_id": "R_kgDOQ6NDkA",
        "notifications_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/notifications{?since,all,participating}",
        "open_issues": 0,
        "open_issues_count": 0,
        "owner": {
            "avatar_url": "https://avatars.githubusercontent.com/u/246072696?v=4",
            "events_url": "https://api.github.com/users/isabelschoeps-thiel/events{/privacy}",
            "followers_url": "https://api.github.com/users/isabelschoeps-thiel/followers",
            "following_url": "https://api.github.com/users/isabelschoeps-thiel/following{/other_user}",
            "gists_url": "https://api.github.com/users/isabelschoeps-thiel/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/isabelschoeps-thiel",
            "id": 246072696,
            "login": "isabelschoeps-thiel",
            "node_id": "U_kgDODqrFeA",
            "organizations_url": "https://api.github.com/users/isabelschoeps-thiel/orgs",
            "received_events_url": "https://api.github.com/users/isabelschoeps-thiel/received_events",
            "repos_url": "https://api.github.com/users/isabelschoeps-thiel/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/isabelschoeps-thiel/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/isabelschoeps-thiel/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/isabelschoeps-thiel",
            "user_view_type": "public"
        },
        "private": false,
        "pulls_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/pulls{/number}",
        "pushed_at": "2026-02-07T23:53:48Z",
        "releases_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/releases{/id}",
        "size": 108,
        "ssh_url": "git@github.com:isabelschoeps-thiel/seismic-source.git",
        "stargazers_count": 0,
        "stargazers_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/stargazers",
        "statuses_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/subscribers",
        "subscription_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/subscription",
        "svn_url": "https://github.com/isabelschoeps-thiel/seismic-source",
        "tags_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/tags",
        "teams_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/teams",
        "topics": [
            "drones-security",
            "github-build-for-a-better-world",
            "human-rights",
            "rescue",
            "seismic",
            "seismic-data",
            "seismic-source",
            "seismic-technology",
            "uav"
        ],
        "trees_url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source/git/trees{/sha}",
        "updated_at": "2026-02-07T23:42:05Z",
        "url": "https://api.github.com/repos/isabelschoeps-thiel/seismic-source",
        "visibility": "public",
        "watchers": 0,
        "watchers_count": 0,
        "web_commit_signoff_required": false
    },
    "sender": {
        "avatar_url": "https://avatars.githubusercontent.com/u/246072696?v=4",
        "events_url": "https://api.github.com/users/isabelschoeps-thiel/events{/privacy}",
        "followers_url": "https://api.github.com/users/isabelschoeps-thiel/followers",
        "following_url": "https://api.github.com/users/isabelschoeps-thiel/following{/other_user}",
        "gists_url": "https://api.github.com/users/isabelschoeps-thiel/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/isabelschoeps-thiel",
        "id": 246072696,
        "login": "isabelschoeps-thiel",
        "node_id": "U_kgDODqrFeA",
        "organizations_url": "https://api.github.com/users/isabelschoeps-thiel/orgs",
        "received_events_url": "https://api.github.com/users/isabelschoeps-thiel/received_events",
        "repos_url": "https://api.github.com/users/isabelschoeps-thiel/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/isabelschoeps-thiel/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/isabelschoeps-thiel/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/isabelschoeps-thiel",
        "user_view_type": "public"
    }
}
